/*
* Generated by XIV.Utils.ClassGenerator
*/
public static class AnimationConstants 
{
	/*
	* Inner Classes
	*/
	public static class AJ 
	{
		// Members
		public const string AJ_Jump = "Jump";
		public const string AJ_Idle = "Idle";
		public const string AJ_Walk = "Walk";
		public const string AJ_Run = "Run";
		public const string AJ_OpenDoor = "OpenDoor";
		public const string AJ_Speed_Float = "Speed";
		public const string AJ_Jump_Bool = "Jump";
		public const int AJ_Base_Layer = 0;
		public const int AJ_Right_Hand_Override_Layer = 1;
	}// class AJ
	public static class Door 
	{
		// Members
		public const string Door_LeftSide_Open = "LeftSide_Open";
		public const string Door_LeftSide_Close = "LeftSide_Close";
		public const string Door_RightSide_Open = "RightSide_Open";
		public const string Door_RightSide_Close = "RightSide_Close";
		public const string Door_LeftSide_Open_Bool = "LeftSide_Open";
		public const string Door_LeftSide_Close_Bool = "LeftSide_Close";
		public const string Door_RightSide_Open_Bool = "RightSide_Open";
		public const string Door_RightSide_Close_Bool = "RightSide_Close";
		public const string Door_AnimationSpeed_Float = "AnimationSpeed";
		public const int Door_Base_Layer = 0;
	}// class Door
	public static class Keycard 
	{
		// Members
		public const string Keycard_KeycardSpin = "KeycardSpin";
		public const int Keycard_Base_Layer = 0;
	}// class Keycard
	public static class TestController 
	{
		// Members
		public const string TestController_DoTransitionToState1_Trigger = "DoTransitionToState1";
		public const string TestController_DoTransitionToState2_Trigger = "DoTransitionToState2";
		public const int TestController_Base_Layer = 0;
	}// class TestController
}// class AnimationConstants

