/*
* Generated by XIV.Utils.ClassGenerator
*/
using UnityEngine;

public static class AnimationConstants 
{
	// Inner Classes
	public static class AJ 
	{
		// Inner Classes
		public static class Clips 
		{
			// Members
			public const string AJ_Jump = "Jump";
			public static readonly int AJ_JumpHash = Animator.StringToHash("Jump");
			public const string AJ_Idle = "Idle";
			public static readonly int AJ_IdleHash = Animator.StringToHash("Idle");
			public const string AJ_StandardWalk = "StandardWalk";
			public static readonly int AJ_StandardWalkHash = Animator.StringToHash("StandardWalk");
			public const string AJ_Run = "Run";
			public static readonly int AJ_RunHash = Animator.StringToHash("Run");
			public const string AJ_RightHandHold = "RightHandHold";
			public static readonly int AJ_RightHandHoldHash = Animator.StringToHash("RightHandHold");
			public const string AJ_RightHandRelease = "RightHandRelease";
			public static readonly int AJ_RightHandReleaseHash = Animator.StringToHash("RightHandRelease");
			
		} // class Clips
		 
		public static class Parameters 
		{
			// Members
			public const string AJ_Speed_Float = "Speed";
			public const string AJ_Jump_Bool = "Jump";
			public const string AJ_RightHandHold_Bool = "RightHandHold";
			public const string AJ_RightHandRelease_Bool = "RightHandRelease";
			
		} // class Parameters
		 
		public static class Layers 
		{
			// Members
			public const int AJ_Base_Layer = 0;
			public const int AJ_Right_Hand_Override_Layer = 1;
			
		} // class Layers
		 
		
	} // class AJ
	 
	public static class Door 
	{
		// Inner Classes
		public static class Clips 
		{
			// Members
			public const string Door_LeftSide_Open = "LeftSide_Open";
			public static readonly int Door_LeftSide_OpenHash = Animator.StringToHash("LeftSide_Open");
			public const string Door_LeftSide_Close = "LeftSide_Close";
			public static readonly int Door_LeftSide_CloseHash = Animator.StringToHash("LeftSide_Close");
			public const string Door_RightSide_Open = "RightSide_Open";
			public static readonly int Door_RightSide_OpenHash = Animator.StringToHash("RightSide_Open");
			public const string Door_RightSide_Close = "RightSide_Close";
			public static readonly int Door_RightSide_CloseHash = Animator.StringToHash("RightSide_Close");
			
		} // class Clips
		 
		public static class Parameters 
		{
			// Members
			public const string Door_LeftSide_Open_Bool = "LeftSide_Open";
			public const string Door_LeftSide_Close_Bool = "LeftSide_Close";
			public const string Door_RightSide_Open_Bool = "RightSide_Open";
			public const string Door_RightSide_Close_Bool = "RightSide_Close";
			public const string Door_AnimationSpeed_Float = "AnimationSpeed";
			
		} // class Parameters
		 
		public static class Layers 
		{
			// Members
			public const int Door_Base_Layer = 0;
			
		} // class Layers
		 
		
	} // class Door
	 
	public static class Keycard 
	{
		// Inner Classes
		public static class Clips 
		{
			// Members
			public const string Keycard_KeycardSpin = "KeycardSpin";
			public static readonly int Keycard_KeycardSpinHash = Animator.StringToHash("KeycardSpin");
			
		} // class Clips
		 
		public static class Layers 
		{
			// Members
			public const int Keycard_Base_Layer = 0;
			
		} // class Layers
		 
		
	} // class Keycard
	 
	public static class TestController 
	{
		// Inner Classes
		public static class Parameters 
		{
			// Members
			public const string TestController_DoTransitionToState1_Trigger = "DoTransitionToState1";
			public const string TestController_DoTransitionToState2_Trigger = "DoTransitionToState2";
			
		} // class Parameters
		 
		public static class Layers 
		{
			// Members
			public const int TestController_Base_Layer = 0;
			
		} // class Layers
		 
		
	} // class TestController
	 
	
} // class AnimationConstants
 

