/*
* Generated by XIV.Utils.ClassGenerator
*/
public static class TagConstants 
{
	// Members
	public const string Untagged = "Untagged";
	public const string Respawn = "Respawn";
	public const string Finish = "Finish";
	public const string EditorOnly = "EditorOnly";
	public const string MainCamera = "MainCamera";
	public const string Player = "Player";
	public const string GameController = "GameController";
	public const string BlackBoard = "BlackBoard";
	public const string SayiGenerator = "SayiGenerator";
	public const string Giris_UI = "Giris_UI";
	public const string Door = "Door";
	public const string Keycard = "Keycard";
	public const string LockedDoor_UI = "LockedDoor_UI";
	
} // class TagConstants
 

